config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "employees#index"
  resources :employees
  resources :main_menu, only: [:index]
  resources :sessions, only: [:create, :destroy]
  resources :products, :path => "productListing"
end

app/models/product.rb
class Product < ApplicationRecord
  validates :lookupCode, presence: true, uniqueness: true

  before_validation :lowerCase, on: :create

  private

  def lowerCase
    self.lookupCode = lookupCode.downcase
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find_by(lookupCode: params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    id = params[:product][:id]
    count = params[:product][:count]
    product = Product.new(lookupCode: id, count: count)

    if product.save
      flash[:noitce] = "Product created"
      redirect_to edit_product_path(id)
    else
      flash[:error] = "Product did not save, please try again"
      redirect_to new_product_path
    end
  end

  def edit
    puts params[:i]
    @product = Product.find_by(lookupCode: params[:id])
    puts @product.lookupCode
    puts @product.count
  end

  def update
    lookupCode = params[:product][:lookupCode]
    count = params[:product][:count]
    product = Product.find_by(lookupCode: lookupCode)
    product.count = count

    if product.save
      flash[:notice] = "Product was successfully saved"
    else
      flash[:error] = "Product was not saved, please try again"
    end
    redirect_to edit_product_path(lookupCode)
  end

  def destroy
    lookupCode = params[:id]

    product = Product.find_by(lookupCode: lookupCode)

    if product.destroy
      flash[:notice] = "Product was deleted"
    else
      flash[:error] = "Product was not deleted, please try again"
    end
    redirect_to products_path
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/edit.html.erb
<%= button_to "Product Listing", products_path, method: :get %>
<%= form_with model: @product, method: "put" do |f| %>
    <%= f.label :lookupCode, "Look-UP Code" %>
    <%= f.text_field :lookupCode, :required => true %></br>
    <%= f.label :count, "Count" %>
    <%= f.text_field :count, :required => true %></br>
    <%= f.submit "Edit" %>
<% end %>
<%= button_to "Delete", product_path, method: :delete %>

app/views/products/index.html.erb
<%= button_to "Main Menu", main_menu_index_path, method: :get %>
<%= button_to "Create New", new_product_path, method: :get %>
<% @products.each do |product| %>
    <%= product.lookupCode %>
    <%= button_to "Show", product_path(product.lookupCode), :method => "get" %>
<% end %>

app/views/products/new.html.erb
<%= form_with model: @product do |f| %>
    <%= f.label :id, "Look-UP Code" %>
    <%= f.text_field :id, :required => true%></br>
    <%= f.label :count, "Count" %>
    <%= f.text_field :count, :required => true%></br>
    <%= f.submit "Create" %>
<% end %>

app/views/products/show.html.erb
<%= button_to "Product Listing", products_path, method: :get %>
<br>
Lookup Code: <%= @product.lookupCode %>
<br>
Product Count: <%= @product.count %>
<%= button_to "Edit", edit_product_path(@product.lookupCode), method: :get %>